cookie:
  expiry_days: 100
  key: f3d9c8a4e2b1478da2f6b5c4de9a78bc
  name: auth_cookie
credentials:
  usernames:
    battlebotsadmin:
      email: BattleBots@gmail.com
      failed_login_attempts: 0
      first_name: Battle
      last_name: Bots
      logged_in: false
      password: $2b$12$BoFaHPGF3zPOwf2oXrPc1OMKr1Y6/0fG4.fYCySoPh2oxcJ7q00i2
      roles:
      - admin
